import type { Metadata } from "next";
import "./globals.css";
import { switchTheme, Theme } from "@/components/themeSwitcher";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme={switchTheme(Theme.dark)}>
      <body
        className={
          "antialiased bg-background dark:bg-dark-background text-foreground dark:text-dark-foreground"
        }
      >
        {children}
      </body>
    </html>
  );
}
